src/lists/urls.py
from django.urls import path
from lists import views

urlpatterns = [
    path("new", views.new_list, name="new_list"),
    path("<int:list_id>/", views.view_list, name="view_list"),
]

src/superlists/urls.py
from django.urls import path, include
from lists import views as list_views

urlpatterns = [
    path("", list_views.home_page, name="home"),
    path("lists/", include("lists.urls")),
]

src/accounts/models.py
from django.db import models


class User(models.Model):
    email = models.EmailField(primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"
    is_anonymous = False
    is_authenticated = True

src/lists/models.py
from django.db import models
from django.urls import reverse

class List(models.Model):
    def get_absolute_url(self):
        return reverse("view_list", args=[self.id])


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    class Meta:
        ordering = ("id",)
        unique_together = ("list", "text")
    

    def __str__(self):
        return self.text

src/lists/forms.py
from typing import Any
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):
    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.widgets.TextInput(
                attrs={
                    "placeholder": "Enter a to-do item",
                    "class": "form-control form-control-lg"
                }
            )
        }
        error_messages = {"text": {"required": EMPTY_ITEM_ERROR}}
    
    def save(self, for_list) -> Any:
        self.instance.list = for_list
        return super().save()

class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list
    

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {"text": [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)


    def save(self):
        return forms.models.ModelForm.save(self)

src/accounts/views.py
from django.shortcuts import render

# Create your views here.

src/lists/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from lists.models import Item, List
from lists.forms import ItemForm, ExistingListItemForm


def home_page(request):
    return render(request, "home.html", {"form": ItemForm()})


def view_list(request, list_id):
    our_list = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=our_list)
    if request.method == "POST":
        form = ExistingListItemForm(for_list=our_list, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(our_list)
    else:
        form = ExistingListItemForm(for_list=our_list)
    return render(request, "list.html", {"list": our_list, "form": form})


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        nulist = List.objects.create()
        form.save(for_list=nulist)
        return redirect(nulist)
    else:
        return render(request, "home.html", {"form": form})
    

src/lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>To-Do lists</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <div class="container">

          <nav class="navbar">
            <div class="container-fluid">
              <a class="navbar-brand" href="/">SuperLists</a>
              <form method="POST" action="/accounts/send_login_email">
                <div class="input-group">
                  <label class="navbar-text me-2" for="id_email_input">
                    Enter your email to log in
                  </label>
                  <input 
                    id="id_email_input"
                    name="email"
                    class="form-control"
                    placeholder="your@email.com"
                  />
                  {% csrf_token %}
                </div>
              </form>
            </div>
          </nav>
    
          <div class="row justify-content-center p-5 bg-body-tertiary rouded-3">
            <div class="col-lg-6 text-center">
              <h1>{% block header_text %}{% endblock %}</h1>
    
              <form method="POST" action="{% block form_action %}{% endblock %}" >
                {% csrf_token %}
                <input 
                  id="id_text"
                  name="text"
                  class="form-control
                         form-control-lg
                         {% if form.errors %}is-invalid{% endif %}"
                  placeholder="Enter a to-do item"
                  value="{{ form.text.value }}"
                  aria-describedby="id_text_feedback"
                  required
                />
                {% if form.errors %}
                  <div id="id_text_feedback" class="invalid-feedback">{{ form.errors.text.0 }}</div>
                {% endif %}
              </form>
            </div>
          </div>
    
          <div class="row justify-content-center">
            <div class="col-lg-6">
              {% block table %}
              {% endblock %}
            </div>
          </div>
    
        </div>
        <script src="/static/lists.js"></script>
        <script>
          window.onload = () => {
            initialize("#id_text");
          }
        </script>
    </body>
</html>

src/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

src/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}